version: "3.8"

services:
  app:
    image: node:latest # Use official Node.js image
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app # Sync local files with the container
      - /usr/src/app/node_modules # Prevent overwriting node_modules
    ports:
      - "3000:3000" # Map container port to host
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install -g pnpm &&
             pnpm install &&
             pnpm dev"
